name: Build, Push, and Deploy Docker Image to Google Cloud Platform

on:
  push:
    branches: [ main ]

jobs:
  build-push-deploy:
    name: Build, Push, and Deploy to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: logoreco
      PROJECT_ID: mlops-437407
      REGION: asia-south1 # Change to your Cloud Run region
      SERVICE_NAME: logo-recognition # Change to your Cloud Run service name
      PORT : 8501

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker Client for GCR
      run: gcloud auth configure-docker --quiet

    - name: Write GCP credentials to JSON file
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > credentials.json

    - name: Build Docker Image
      run: docker build \
        --build-arg GOOGLE_APPLICATION_CREDENTIALS=credentials.json \
        -t $IMAGE_NAME:latest .

    

    - name: Push Docker Image to Google Container Registry (GCR)
      run: |
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$IMAGE_NAME:latest \
          --platform managed \
          --region $REGION \
          --port "${{ env.PORT }}" \
          --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=credentials.json \

    - name: Set IAM Policy to Allow Public Access
      run: |
        gcloud run services add-iam-policy-binding $SERVICE_NAME \
          --region=$REGION \
          --member="allUsers" \
          --role="roles/run.invoker"

          
